# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://mithun05.github.io/
baseurl: /portfolio/
title: Mithun Deshpande
author: Mithun Deshpande
description: Personal blog and resume
avatar: profile.png
email: mdeshpa1@binghamton.edu
github: Mithun05/ # username
twitter: mgd2171991
linkedin: mithun-deshpande
stackoverflow: users/4387633/md05   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
